### ISSUE TITLE
Change font typeface on chip view

### ISSUE THREAD

**Issue by bikramtemp** [robertlevonyan/materialChipView#10]
There is no method to set typeface on the chip view like we have on textview or button

**Comment by robertlevonyan** [comment]
Yeah right now it is using only default typeface of android

**Comment by bikramtemp** [comment]
any way to update the font of text in chipview?

**Comment by robertlevonyan** [comment]
Not at this moment. But please follow the updates. Soon there will be a new version, with more options for customizations like corner radius, border color, custom typeface, etc.

**Comment by bikramtemp** [comment]
ok thanks

**Comment by pcegarra** [comment]
Waiting for custom font...

**Comment by AlexRU18** [comment]
Still waiting custom textsize or font..

**Comment by HamidrezaAmz** [comment]
custom font...
