### ISSUE TITLE
No Resource Identifier Found

### ISSUE THREAD

**Issue by ZeroGrvty** [robertlevonyan/materialChipView#13]
When I try to add the chip via xml i keep getting the error
`Error:(70) No resource identifier found for attribute 'mcv_chipIcon' in package 'com.test.testertest'`
here is the xml: 
`<com.robertlevonyan.views.chip.Chip
            android:id="@+id/basketball_chip"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/activity_vertical_margin"
            app:mcv_backgroundColor="@color/colorBasketball"
            app:mcv_chipIcon="@drawable/basketball"
            app:mcv_chipText="@string/basketball"
            app:mcv_closeColor="@color/primaryColor"
            app:mcv_hasIcon="true"
            app:mcv_selectable="true"
            app:mcv_selectedBackgroundColor="@color/colorBasketballSelected"
            app:mcv_textColor="@color/colorBasketballSelected" />`

**Comment by robertlevonyan** [comment]
Hi, use attribute chipIcon instead of mcv_chipIcon. In the new version the attributes names will be changed. Sorry for that :)

**Comment by ZeroGrvty** [comment]
Thank you very much! I love this library.

**Comment by robertlevonyan** [comment]
Thank you so much :)
