### ISSUE TITLE
Error:(10) No resource identifier found for attribute 'mcv_chipText' in package 

### ISSUE THREAD

**Issue by amankumarjain** [robertlevonyan/materialChipView#14]
I'm using android 4.4, how to solve this error?

**Comment by robertlevonyan** [comment]
please use chipText instead of mcv_chipText. The attribute names will be changed in the new version of lib. Thanks ))

**Comment by amankumarjain** [comment]
still not working with horizontal recycler view, chip view is not visible in holder

**Comment by robertlevonyan** [comment]
Can you send your code?
