### ISSUE TITLE
How do I change the text size of a chip?

### ISSUE THREAD

**Issue by rinav** [robertlevonyan/materialChipView#18]

**Comment by robertlevonyan** [comment]
Actually it's not possible. Because in the Material Design Guidelines there is exact text size for Material Chip View.

**Comment by Bringoff** [comment]
@robertlevonyan but what if my designer doesn't wanna adhere guidelines strictly? :) Or I just wanna use this library for some customised tags view? I think text size changing is required, it should not be difficult to add.

**Comment by robertlevonyan** [comment]
Definitely it's not difficult, but the main reason of creating this lib, to have almost the same view as described in Material design guidelines ))

**Comment by AtthaponKorkaew** [comment]
You know what happen when text on chip too long for single line.
Please check it.
