### ISSUE TITLE
AppTheme conflicts

### ISSUE THREAD

**Issue by bpappin** [robertlevonyan/materialChipView#24]
I would rename your Theme to match the name of the component, to avoid conflicts with apps.

`
Error:Execution failed for task ':my-widget:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme.MyAppTheme) from [__tested_artifact__::my-widget] AndroidManifest.xml:15:9-50
  	is also present at [com.robertlevonyan.view:MaterialChipView:1.1.2] AndroidManifest.xml:16:9-40 value=(@style/AppTheme).
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at manifestMerger3134971992410343730.xml:7:5-9:19 to override.`

**Comment by robertlevonyan** [comment]
Just add tools:replace="android:theme" to your <application> element

**Comment by bpappin** [comment]
Of course i can, thats exactly what I have done, but it's not a fix, there is no way a library should be forcing the app to apply some workaround, especially for such a simple fix.
