### ISSUE TITLE
How to add a group of chipviews?

### ISSUE THREAD

**Issue by DanteAndroid** [robertlevonyan/materialChipView#26]
I think this chipview is beautiful, but I need something like [this](https://camo.githubusercontent.com/8adbb5c44c656151cb108ada6d1383e2c6af38b7/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f62636532646561396a7731657362736279397635666a323075303077386a78782e6a7067)
Can you tell me how to add them dynamically

**Comment by robertlevonyan** [comment]
You can use this with flexbox layout or recycler view
