### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by DanteAndroid** [robertlevonyan/materialChipView#27]
1. When selected the first time, the chip becomes selected then unselected suddenly.
2. When setOnSelectClickListener in code, then chip has a weired icon(or text?)
3. The chip can be selected only on tick icon(I think the chip can be selected by clicking all area of it makes more sense)

And for 3, I hope you can provide a method to control if the tick icon shows.
Here is the demo. Thanks for your time, I like your repo!
[demo.zip](https://github.com/robertlevonyan/materialChipView/files/1493779/demo.zip)

**Comment by robertlevonyan** [comment]
you can select the chip only from tick icon, because you can also have another click action for chip.
for 1 and 2 issues can you send the code for only this parts

**Comment by DanteAndroid** [comment]
Not sure how to send a single file in Pull Request, so just send file here.
What I changed:
- Fix 1(Select state is fine, code optimized);
- Fix 3(You can setHasSelectIcon, default is false, if set true, then tick icon control if selected or not)

 
[归档.zip](https://github.com/robertlevonyan/materialChipView/files/1497858/default.zip)

**Comment by DanteAndroid** [comment]
[Chip.java.zip](https://github.com/robertlevonyan/materialChipView/files/1498144/Chip.java.zip)
Fix `setSelected` doesn't work at runtime

**Comment by DanteAndroid** [comment]
New Bug: `setChipText` not work at runtime. Don't know how to fix.

**Comment by robertlevonyan** [comment]
how do you use it?

**Comment by DanteAndroid** [comment]
just `chip.setChipText(text);`

I read the source code:
```
    public void setChipText(String chipText) {
        this.chipText = chipText;
    }
```
It doesn't change UI.

**Comment by robertlevonyan** [comment]
is it in recyclerview or somewhere else?

**Comment by DanteAndroid** [comment]
It's in XML layout.

**Comment by robertlevonyan** [comment]
so you mean you're setting text from xml?

**Comment by DanteAndroid** [comment]
I said at runtime, it means I `setChipText` in an Activity. But chip view is placed in XML (not created at Activity)

**Comment by robertlevonyan** [comment]
update to the latest version of lib and recheck your code. it works. if there still will be any problems. share your code

**Comment by DanteAndroid** [comment]
Are you kidding me? Are you telling me that ` public void setChipText(String chipText) {
        this.chipText = chipText;
    }` can change the appearance? I must be a fake programmer

**Comment by robertlevonyan** [comment]
yes beacause it's calling onSizeChange method of the View. Look the documentation of View's lifecycle
