### ISSUE TITLE
Use of chip in recyclerview

### ISSUE THREAD

**Issue by blackchineykh** [robertlevonyan/materialChipView#32]
Hi, I like this library and its the best impementation of Material Chip that i've found so far. My only issue now is that i have an adapter that has a viewholder with Chip as a view in the XML. 

Whenever i set the chip text using chip.setChipText(item.getCategory()); it seems that after scrolling through a few items in the view, the text on the chip starts to get jumbled and seems its overlapping with the previous values from other categories. Is there a way to ensure we clear the previous value that was set for the chip so it displays correctly as you scroll up or down the list of items in the recyclerview?

See sample below
![image](https://user-images.githubusercontent.com/10213391/34458508-6e39a254-eda3-11e7-9cdf-2e366b7131da.png)

Thanks.

**Comment by robertlevonyan** [comment]
Add this to your adapter

    @Override
    public long getItemId(int position) {
        return position;
    }
