### ISSUE TITLE
Selected - by click on whole chip

### ISSUE THREAD

**Issue by lifeisdream** [robertlevonyan/materialChipView#35]
It sometimes can be not easy to touch exactly into selected icon on the right of the chip.
Maybe it would be useful to be able to select \ deselect chip by clicking at an entire chip.
Can't to it via Chip Click Listener because in that case if I touch it in selected icon - the behavior will merge.

**Comment by robertlevonyan** [comment]
yes because there two custom behaviors for chip click and chip select
