### ISSUE TITLE
Chip View not appearing in RecyclerView layout

### ISSUE THREAD

**Issue by ElyDantas** [robertlevonyan/materialChipView#38]
Simple `<com.robertlevonyan.views.chip.Chip>` XML body in my recyclerview adapter layout does not show when it's inside recyclerview. It works ok in other layout that are not inside a recyclerview.

**Comment by Vasyka** [comment]
It's okey for me. Did you add `Chip chip = (Chip) findViewById(R.id.chip)` to your adapter for recyclerview?

**Comment by robertlevonyan** [comment]
update to version 1.2.0
