### ISSUE TITLE
The inner views are created several times

### ISSUE THREAD

**Issue by fabionuno** [robertlevonyan/materialChipView#4]
### What You Are Seeing?
The `buildView()` method is called multiple times during the initialization process, the first one by the constructor, the second in `onAttachedToWindow()` and finally in `onSizeChanged()`, creating the inner views several times.
![viewshierarchy](https://cloud.githubusercontent.com/assets/5355384/23810036/ad457690-05ae-11e7-9f25-17db93ffe16c.png)

### What is Expected?
The inner views

 hierarchy needs to be created only one time

### What environment are you running on?
Emulator with Android 7.1.1 Google APIs

**Comment by robertlevonyan** [comment]
I'm using Android 6.0.1 and Android 7.0. The recreation is happening because on Android 7 onSizeChanged() is not working correctly in this case, so I'm using also onAttachedToWindow() also

**Comment by fabionuno** [comment]
Anyway multiple views would be created in versions lower than Android 7, since the `buildView()` was called by the constructor and by `onSizeChanged()`

**Comment by robertlevonyan** [comment]
I made an update for library. Now I think there is no recreation and calling of the buildView() in different methods of life-cycle depends on android version

**Comment by fabionuno** [comment]
Unfortunately these changes haven't fixed the problem.
The `onSizeChanged()` is called during layout when the size of this view has changed.
Since you are adding new views to the hierarchy that changes the size of view, the `onSizeChanged()`  will be triggered again, creating the inner views again.

You can check this using the Layout Inspector of Android Studio.
