### ISSUE TITLE
 Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by jitarun** [robertlevonyan/materialChipView#41]
Hi,
This an awesome library. i need to implement but  i'm facing this issue
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by robertlevonyan** [comment]
Do a cleab build

**Comment by jitarun** [comment]
i created a new project and implemented this lib its working fine.but my project having this issue anyway thanks for reply.

**Comment by robertlevonyan** [comment]
Cleaning the project should help

**Comment by jitarun** [comment]
Hi @robertlevonyan i have found this error, "attribute application@icon value=(@mipmap/ic_launcher) from androidmanifest.xml" on Merged Manifest tab.

then i have changed  added my manifest file, ' tools:replace="android:icon" ' to  application tag. It will solved the issue.

<application
    android:name=".ApplicationSubClass"
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@android:style/Theme.Holo.Light"
    tools:replace="android:icon" > //HERE

**Comment by jitarun** [comment]
<application
    android:name=".ApplicationSubClass"
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@android:style/Theme.Holo.Light"
    tools:replace="android:icon" > //HERE

**Comment by robertlevonyan** [comment]
Looks like you have some view which have same android:icon attribute, for Chip use app:mcv_chipIcon
