### ISSUE TITLE
Add to jitpack.io

### ISSUE THREAD

**Issue by Coehill** [robertlevonyan/materialChipView#48]
If this library was added to jitpack.io then it could be added to a project with a single `implementation` line in the app level build.gradle and searchable on jitpack.  It looks like it's getting an error for the latest commit `150266c`there:  https://jitpack.io/#robertlevonyan/materialChipView

**Comment by Coehill** [comment]
First, add the JitPack repository to your root build.gradle at the end of repositories

	
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}


and then add the dependency:

	dependencies {
	        compile 'com.github.robertlevonyan:materialChipView:-SNAPSHOT'
	}

Maybe use this in the README instead?

**Comment by daberni** [comment]
it's already on bintray which is available via `jcenter()`
jitpack just hosts snapshots which aren't final releases
