### ISSUE TITLE
[Feature request] Click to switch select state

### ISSUE THREAD

**Issue by SoyaLeaf** [robertlevonyan/materialChipView#52]
The selectIcon is a bit small.

Why not switch ‘select’ status by clicking?

:)

**Comment by robertlevonyan** [comment]
because you can have both selecting and clicking options :)

**Comment by SoyaLeaf** [comment]
@robertlevonyan 
Hi,thanks for the reply.
But I think ‘selectIcon’ is too small to click. It may be possible to add a attribute that allows the user to choose whether to use 'selectIcon' or to switch the select state by clicking.

**Comment by root-ansh** [comment]
is there a clickable option too? how can i get that? I am not liking this small selection icon. I too want to  make the whole chip selectable
