### ISSUE TITLE
ChipGroup [ENHANCEMENT]

### ISSUE THREAD

**Issue by Akshshr** [robertlevonyan/materialChipView#56]
Hey there,

Cool library, but I think to make it really dynamic and usable, I think making a separate component thats ChipGroup which would make it much easier to have several of these, in a radio/multi select options

Thanks again! 
Regards

**Comment by robertlevonyan** [comment]
Hi @Akshshr .
Great idea! I think that would be a cool addition to me lib :+1:

**Comment by robertlevonyan** [comment]
Yeah actually they've created very similar to my library Chip View. 

Good luck :+1:
