### ISSUE TITLE
Chip need to call requestLayout for show correctly

### ISSUE THREAD

**Issue by mahdiyaroraei** [robertlevonyan/materialChipView#6]
Hi
I use chip in FlexBoxLayout that design by google and when call addView on layout, chip's appears without anything and just show empty box and need to call requestLayout to show this content
```java
Handler handler = new Handler();
handler.postDelayed(new Runnable() {
        @Override
        public void run() {
                chip.requestLayout();
        }
}, 250);
```

what's wrong?

**Comment by robertlevonyan** [comment]
Have you add some text to chip?

**Comment by mahdiyaroraei** [comment]
yes

**Comment by robertlevonyan** [comment]
You haven't set LayoutParams to Chip

**Comment by dayanithi06** [comment]
Not only flex layout. When dynamically inflating chip into linearlayout also it shows empty views. Any Fixes?

**Comment by robertlevonyan** [comment]
Do you have a screenshot?

**Comment by dayanithi06** [comment]
private void inflateGenerated() {
        LayoutInflater vi = (LayoutInflater) getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        LinearLayout insertPoint = (LinearLayout) findViewById(R.id.layoutTags);
       insertPoint.removeAllViews();
        for (int i = 0; i < autoGeneratedList.size(); i++) {
// fill in any details dynamically here
            final Chip chip = (Chip) vi.inflate(R.layout.item_chip, insertPoint, false);
            chip.setChipText(autoGeneratedList.get(i));
     
            insertPoint.addView(chip);
        }

    }

//xml
<?xml version="1.0" encoding="utf-8"?>
<com.robertlevonyan.views.chip.Chip xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:closable="true"
    android:layout_margin="10dp"
    app:backgroundColor="@color/blue"
    app:closeColor="@color/white"
    app:textColor="@color/white" />

**Comment by robertlevonyan** [comment]
Okay​. I'll check this and I'll provide an update to lib. Thanks :)

**Comment by Steepo** [comment]
android:id="@+id/chip"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:mcv_chipText="@string/customTitle"
                    app:mcv_selectable="true"
The Chip doest not show properly, please fix, i love the library 
![device-2017-06-13-174041](https://user-images.githubusercontent.com/17814298/27091126-859fc4be-505f-11e7-86bd-57a00b515bf0.png)

**Comment by robertlevonyan** [comment]
whats the problem here? You haven't set chiptext and image

**Comment by Khoosham** [comment]
same here its blank i have a listview and add chip to the row.
my xml as follows:

```
<com.robertlevonyan.views.chip.Chip
        android:id="@+id/chip"
        android:layout_width="40dp"
        android:layout_height="20dp"
        android:layout_marginTop="5dp"
        android:layout_marginRight="15dp"
        android:layout_marginEnd="15dp"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        app:mcv_hasIcon="false"
        app:mcv_closable="false"
        app:mcv_chipText="...." />
```

when the list is created the chip appears but with no text i need to scroll the view down and up for the text to appear, i am setting the text in my custom adapter on View getView() like this

```
@Override
    public View getView(int position, View convertView, ViewGroup parent) {
other code here....... and below this
 viewHolder.chip.setChipText("LIVE");
 viewHolder.chip.setTextColor(Color.RED);
return row
}
```

the output is the like above in @Steepo  screenshot it has no text

**Comment by Steepo** [comment]
Text does not appear either by setting it from XML or via code

**Comment by robertlevonyan** [comment]
ok let me check and provide a solution. thanks ))

**Comment by robertlevonyan** [comment]
Now try to us chipText instead of mcv_chipText

**Comment by Khoosham** [comment]
how to use chipText you did not make any change to the code ?

**Comment by robertlevonyan** [comment]
Not yet :) I'm a bit busy at this moment. But I'll fix all the issues )))

**Comment by ExCx** [comment]
Yeah, adding chips by code doesn't work without the Handler solution of @mahdiyaroraei , thanks for showing that.

Changing fragments also make the chips disappear, so the app must remember the added chips in the previous fragment and add them again in onCreateView every time.

This is a great library. All other chip libraries are coming with an embedded EditText and I don't want that, so I'll still use this. So, Robert, thanks and keep up the good work, we're counting on you pal :)

**Comment by robertlevonyan** [comment]
@ExCx  thanks. I'll try to update this view quickly.

**Comment by Tenkei7** [comment]
This issue still exists in the latest version (1.2.1).

**Comment by robertlevonyan** [comment]
Check new version (1.2.2) I've tested on several devices API 19+, everithing works
