### ISSUE TITLE
changeBackgroundColor doesn't work

### ISSUE THREAD

**Issue by sathinduga** [robertlevonyan/materialChipView#62]
I have used changeBackgroundColor to change the background color programmatically and it does not change the color.

**Comment by catual** [comment]
did you pass the right int with 

`chip.changeSelectedBackgroundColor(context.getResources().getColor(R.color.colorAccent) )`

**Comment by cbnewham** [comment]
I could be wrong, but it seems your chips are not dynamically updatable.

For instance, setChipText() just sets the internal String - it doesn't actually request any redraws or resizing.

Same for all the other setters!

**Comment by viktordanov** [comment]
@cbnewham I think you're right I just updated my issue and it describes the same problem #64
