### ISSUE TITLE
#setClosable and #setChipText not updating after being initialized 

### ISSUE THREAD

**Issue by viktordanov** [robertlevonyan/materialChipView#64]
I attempted to change a chip's text and also to make it closeable programmaically only to find out nothing actually changed.

I dug deeper, moved the calls to the end of **onCreate** (after initializing the chip view) like so:
```
onCreate() {

  mChip = (Chip) findViewById(R.id.chip);
  
  . . .

  mChip.setChipText("Test");
  mChip.setClosable(true);
```
This functioned as expected and the chip's text was indeed set to "Test" upon opening the app.

The real problem comes when I attempt to change a chip's text after it's been initialized, e.g. in an OnChipClicked handler or anywhere else really. Upon inspecting the source, it appears that on [Code.java:351](https://github.com/robertlevonyan/materialChipView/blob/3e984ffd9348e33be6fbe1052aed92bdd4bf4072/Chip/app/src/main/java/com/robertlevonyan/views/chip/Chip.java#L351) the private field `chipText` is set and is never used by anything else other than the initial initialization by `buildView() -> initTextView() -> chipTextView.setText(chipText);` in `onAttachedToWindow()`;

I patch this by adding `if (this.chipTextView != null) this.chipTextView.setText(chipText);` after [Code.java:351](https://github.com/robertlevonyan/materialChipView/blob/3e984ffd9348e33be6fbe1052aed92bdd4bf4072/Chip/app/src/main/java/com/robertlevonyan/views/chip/Chip.java#L351);

Other functions exhibit similar behavior: #setTextColor(), #setClosable() etc.

It seems as though the chips aren't meant to be updated but rather removed and readded to a layout, is this the intended use or have I misunderstood the code?

**Comment by robertlevonyan** [comment]
@viktordanov thanks for the solution, I've created a new update v.1.2.5
