### ISSUE TITLE
chip.setSelected() doesn't update view

### ISSUE THREAD

**Issue by makbn** [robertlevonyan/materialChipView#65]
hi, I tried to change the state of the chip by calling `setSelected` method inside onClickListener od chip but the chip view doesn't update to selected format!

```java 
chip.setOnChipClickListener(new OnChipClickListener() {
            @Override
            public void onChipClick(View v) {
                Chip t = ((Chip)v);
                boolean selected = t.isSelected();
                boolean isInner = ((String)t.getTag()).equals("inner");
                if(!selected && isInner){
                    AddPropertyManager.addInnerEq(s);
                    t.setSelected(true);
                }else if(selected && isInner){
                    AddPropertyManager.removeInnerEq(s);
                    t.setSelected(false);

                }

                if(!selected && !isInner){
                    AddPropertyManager.addOuterEq(s);
                    t.setSelected(true);

                }else if(selected && !isInner){
                    AddPropertyManager.removeOuterEq(s);
                    t.setSelected(false);
                }
            }
        });
```

how can I update the chips view to the selected format programmatically?

**Comment by robertlevonyan** [comment]
What is your version of Chip?

**Comment by robertlevonyan** [comment]
instead of this Chip t = ((Chip)v) try using the chip instance you have

**Comment by makbn** [comment]
> What is your version of Chip?

version is `1.2.4` i read a closed issue that you said to use new `1.2.5` version but after adding new version i got exception on building because the base of my project uses old versions of libraries and not match with the last version u released!

>  instead of this Chip t = ((Chip)v) try using the chip instance you have

i think its not a good idea to save array of reference to each chipView! why should i do that when i use `V` ?

**Comment by makbn** [comment]
to easy way out from this problem i invoked your library private methods to keep chip style update! but i know its not a robust!

**Comment by robertlevonyan** [comment]
I think is always a good idea to keep the project up to date with gradle :)
I'm keeping the issue open for some time, please try the new version

**Comment by makbn** [comment]
ok ill handle it! thank you 👍
