### ISSUE TITLE
i can add Padding

### ISSUE THREAD

**Issue by oscarshaitan** [robertlevonyan/materialChipView#7]
`Chip  c = new Chip(getApplicationContext());
c.setChipText(AOBJ.getAuthorized_users().get(0));
c.setPadding(1,1,1,1);
c.setClosable(true);
c.changeBackgroundColor(getResources().getColor(R.color.colorAccent));

Chip  b = new Chip(getApplicationContext());       
b.setChipText(AOBJ.getAuthorized_users().get(0));        
b.setClosable(true);        
b.changeBackgroundColor(getResources().getColor(R.color.colorAccent));        
b.setPadding(2,2,2,2);`

![7](https://cloud.githubusercontent.com/assets/9093952/24431982/cfec91f8-13e4-11e7-8dab-90379fc69899.jpg)

no matter what padding.
I´m adding the chips on a gridLayout

**Comment by robertlevonyan** [comment]
try margins instead of paddings

**Comment by oscarshaitan** [comment]
that works con xml, but I´m adding dynamic way, any idea there?

**Comment by oscarshaitan** [comment]
GridLayout.LayoutParams Lp = new GridLayout.LayoutParams();
        Lp.leftMargin = 1;
        Lp.rightMargin = 1;
        Lp.topMargin = 1;
        Lp.bottomMargin = 1;

userLay.addView(c, Lp);

solve with that

**Comment by robertlevonyan** [comment]
Good
