### ISSUE TITLE
Icon Scale Type

### ISSUE THREAD

**Issue by sagarnayak** [robertlevonyan/materialChipView#70]
I want to set a drawable which might be too big or too small as the chip icon. so how do I set a scale type to the image view so that any size of the image would fit well?

**Comment by robertlevonyan** [comment]
By default scale type is FIT_CENTER, so you cannot change it.

**Comment by sagarnayak** [comment]
so what should be an ideal size for the drawable to fit properly?

**Comment by robertlevonyan** [comment]
ideal size is 24dp x 24dp, but you can create a resized bitmap and use it.
