### ISSUE TITLE
Add Multiple chip views programmatically

### ISSUE THREAD

**Issue by saadbzu** [robertlevonyan/materialChipView#72]
How i add chip views programmatically. For example i want 5 chips with different text and i set in a for loop.

**Comment by robertlevonyan** [comment]
You can create instance like this `val chip = Chip(context)`.

**Comment by saadbzu** [comment]
@robertlevonyan Please give an example in java..

**Comment by robertlevonyan** [comment]
`Chip chip = new Chip(context);`
