### ISSUE TITLE
Chips are just gray

### ISSUE THREAD

**Issue by autorunman22** [robertlevonyan/materialChipView#79]
I'm trying to make dynamic chips:
![image](https://user-images.githubusercontent.com/4214419/107148952-f3b71080-6990-11eb-959f-ab4f4bd8d328.png)

But they all turned gray (please see the redbox)
![image](https://user-images.githubusercontent.com/4214419/107148965-06c9e080-6991-11eb-8a60-ed195d4893e4.png)

v2.0.4

**Comment by robertlevonyan** [comment]
please update to the latest version

**Comment by autorunman22** [comment]
> please update to the latest version

I did but almost nothing has changed. I just saw a checked icon this time.

**Comment by robertlevonyan** [comment]
you are setting the colors in wrong way, instead of setting resource names, set the colors. `ContextCompat.getColor(context, R.color.blue)`.

**Comment by autorunman22** [comment]
> you are setting the colors in wrong way, instead of setting resource names, set the colors. `ContextCompat.getColor(context, R.color.blue)`.

 That solved the issue. Thanks!
