### ISSUE TITLE
Use custom attributes?

### ISSUE THREAD

**Issue by fmontesino** [robertlevonyan/materialChipView#8]
Hi, I would love to use your awesome library but it's conflicting with another one already in my project:

Error:(778) Attribute "textColor" already defined with incompatible format.
Error:(586) Original attribute defined here.

Maybe using custom attr names will fix it?

Thanks in advance!

**Comment by robertlevonyan** [comment]
Hi. Thanks for using my library.

You can use custom attr with my library or with another one

**Comment by fmontesino** [comment]
Hey thanks for the fast answer!
What I really meant is I cannot use the library "as is" since its colliding with another one.
For now I have forked it and changed the styleable attrs by hand, but I was wondering if you plan to do so?

Thanks again!!

**Comment by robertlevonyan** [comment]
no I have no plans changing the styleable. But I will do more improvements and I will add more flexibility to library. Just follow the updates

**Comment by fmontesino** [comment]
Cool thanks!

BTW, don't forget to update the library on bintray ;)

**Comment by robertlevonyan** [comment]
Sure 👍
