### ISSUE TITLE
Can't use version 3.0.6 for ChipView

### ISSUE THREAD

**Issue by ElianFabian** [robertlevonyan/materialChipView#85]
When I add this depedency:

```
implementation 'com.robertlevonyan.compose:materialchip:3.0.5'
```

I works fine, but when I change the version to 3.0.6 I have no longer access the Chip view. But I do have access to the compose version of the Chip, which I don't think it should be the case.

**Comment by robertlevonyan** [comment]
For regular chip you need to use `3.0.5`.
